### ISSUE TITLE
Ensure Content-Length header instead of TE: chunked

### ISSUE THREAD

**Issue by malud** [avenga/couper#163]
Since we know the length of the given body bytes for each direction we should ensure sending the `Content-Length` header instead of sending those bytes with `Transfer-Encoding: chunked`.

Depends on the `io.Reader`. StringReader for example triggers an implicit set...

**Comment by filex** [comment]
Sending T/E chunked also leads to problems with the `oauth2` function when used to obtain a token from the MS Graph API (`https://login.microsoftonline.com`): The API responds with a 404 for the token endpoint. Seems like a `content-length` is mandatory.

we should at least switch to `content-length` for all (upstream) requests. because chunked encoding is rather unusual for uploads.

for responses, I wouldn't mind to use chunked encoding.
