### ISSUE TITLE
OpenAPI: resolve servers: relative url with backend origin

### ISSUE THREAD

**Issue by malud** [avenga/couper#164]
The OpenAPI file may have defined servers with urls which could be absolute or relative. This leads to invalid requests for relative ones. We must add the current backend origin host to the relative OpenAPI server url.

Implementation: Since the backend origin gets evaluated during runtime the openAPI configuration must move to a runtime factory.

**Comment by filex** [comment]
I cannot reproduce this issue anymore. My schema looks like this:

```
openapi: 3.0.0
info:
  title: API
  description: This is the write-dm API specification for the frontend.
  version: '1.0'
servers:
  - url: https://api.com/
  - url: /
```

The second url (`/`) works in my case. So the actual absolute URL is ignored. When I remove the relative URL, my particular request fails, because it doesn't match the `https://api.com/` prefix. If I change that to the correct origin, the request is successfully validated.

This works as expected.
