### ISSUE TITLE
settings from configuration file gets ignored

### ISSUE THREAD

**Issue by malud** [avenga/couper#61]
Except the `default_port` option all other possible attributes from the `settings` block needs to be merged with the default http configuration (default ->  flag -> env).

**Comment by filex** [comment]
still, the `-log-format json` setting is only available as flag anymore. both env (`COUPER_LOG_FORMAT`) and `settings { … }` are ignored.

we have `ENV COUPER_LOG_FORMAT=json` in our `Dockerfile`. since the 0.4 release, this does not work anymore. because of this, the default behaviour of the docker container has changed. it logs unstructured text instead of json now.
